### ISSUE TITLE
Improve HEAD CSS

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-pageimage#37]
Hallo Andreas, im Template mod_background_image https://github.com/terminal42/contao-pageimage/blob/master/templates/mod_background_image.html5#L3-L9 hast du dieses CSS.
```css
html {
  background: url("<?php echo specialchars($this->src); ?>") no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
```
Damit kann man aber kein `background-color` und andere background-Eigenschaften für HTML mehr aufsetzen. Könntest du dies wie folgt abändern? Die Präfixe sind IMHO mittlerweile auch überflüssig.
```css
html {
  background-image: url("<?= specialchars($this->src) ?>");
  background-repeat: no-repeat;
  background-position: center;
  background-attachment: fixed;
  background-size: cover;
}
```
Danke.
