### ISSUE TITLE
no support for webp?

### ISSUE THREAD

**Issue by NinaG** [terminal42/contao-pageimage#42]
It seems, that I cannot choose a webp-image in the pageimage-feature. How can I change that? I added webp to allowed file types in Contao settings.

**Comment by Toflar** [comment]
It has to be part of the `validImageTypes` (the new configuration value is `contao.image.valid_extensions`. Are you running the latest version of Contao?

**Comment by NinaG** [comment]
Contao 4.4 LTS.

Ich habe in den Systemeinstellungen bei den "Erlaubte Download-Dateitypen" und bei "Erlaubte Upload-Dateitypen" jeweils "webp" ergänzt. Dennoch keine Möglichkeit beim Bild der Seite in der Seitenstruktur ein webp-Bild auszuwählen.

**Comment by aschempp** [comment]
`validImageTypes` is not "Erlaubte Download-Dateitypen" or "Erlaubte Upload-Dateitypen" 😉

**Comment by Toflar** [comment]
Wie gesagt, diese Einstellungen haben nichts mit dem Problem zu tun. Es geht um die validen Bildtypen. Und da fehlt `webp` in der 4.4.
Du kannst sie hinzufügen mit

```yaml
# config.yml
contao:
    image:
        valid_extensions: ['jpg', 'jpeg', 'gif', 'png', 'tif', 'tiff', 'bmp', 'svg', 'svgz', 'webp']
```

Aber Contao kann sie halt nicht verarbeiten.
